import { Inter } from 'next/font/google';
import Head from 'next/head';
import Link from 'next/link';

import { Navbar } from '@/components/Navbar';
import styles from '@/styles/Home.module.css';

const inter = Inter({ subsets: ['latin'] });

export default function Contact() {
  return (
    <>
      <Head>
        <title>Create Next Contact Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <main className={`${styles.main} ${inter.className}`}>
        <h1 className={styles.title}>Contact Page</h1>
        <Link href="/">
          Go to <code className={styles.code}>pages/index.js</code>
        </Link>
      </main>
    </>
  );
}
